CREATE TABLE PROPIETARIO(rut VARCHAR2(10),
                        nombre VARCHAR2(45),
                        apellido VARCHAR2(45),
                        correo VARCHAR2(45));
                        
ALTER TABLE PROPIETARIO ADD CONSTRAINT PR_RU_PK PRIMARY KEY(rut);

ALTER TABLE PROPIETARIO MODIFY nombre CONSTRAINT PR_NO_NN NOT NULL;
ALTER TABLE PROPIETARIO MODIFY apellido CONSTRAINT PR_AP_NN NOT NULL;
ALTER TABLE PROPIETARIO MODIFY correo CONSTRAINT PR_CO_UN UNIQUE;

INSERT INTO PROPIETARIO VALUES('111-1', 'JUAN', 'PEREZ', 'JP@DUOC.CL');
INSERT INTO PROPIETARIO VALUES('222-2', 'OMAR', 'FUENTES', 'OFUENTES@DUOC.CL');
-- 4 MÁS --
INSERT INTO PROPIETARIO VALUES('333-3', 'MARCO', 'SOLIS', 'MS@DUOC.CL');
INSERT INTO PROPIETARIO VALUES('444-4', 'JACK', 'RIPPER', 'JR@DUOC.CL');
INSERT INTO PROPIETARIO VALUES('555-5', 'JAIME', 'MARQUES', 'JM@DUOC.CL');
INSERT INTO PROPIETARIO VALUES('666-6', 'TANTAN', 'POMPOM', 'TP@DUOC.CL');

-- CREAR LA CLAVE FORANEA --

ALTER TABLE PROPIEDAD ADD rut VARCHAR2(10);

ALTER TABLE PROPIEDAD ADD CONSTRAINT PR_RU_FK FOREIGN KEY (rut) REFERENCES PROPIETARIO(rut);

UPDATE PROPIEDAD SET RUT='111-1' WHERE ROL=11111;
UPDATE PROPIEDAD SET RUT='222-2' WHERE ROL=22222;
UPDATE PROPIEDAD SET RUT='333-3' WHERE ROL=33333;
UPDATE PROPIEDAD SET RUT='444-4' WHERE ROL=44444;
UPDATE PROPIEDAD SET RUT='555-5' WHERE ROL=55555;
UPDATE PROPIEDAD SET RUT='666-6' WHERE ROL=66666;
UPDATE PROPIEDAD SET RUT='222-2' WHERE ROL=77777;
UPDATE PROPIEDAD SET RUT='111-1' WHERE ROL=88888;

SELECT * FROM PROPIEDAD;

