-- Crear la tabla AUTOMOVIL
CREATE TABLE AUTOMOVIL(patente VARCHAR2(10),
                       color VARCHAR2(20),
                       n_asiento NUMERIC(2),
                       pais VARCHAR2(30),
                       año NUMERIC(4));
                       
-- Crearemos las constraints
-- -- Asigna patente como primary key
ALTER TABLE AUTOMOVIL ADD CONSTRAINT AU_PA_PK PRIMARY KEY(patente);
-- -- Deja en no nulos estos atributos
ALTER TABLE AUTOMOVIL MODIFY color CONSTRAINT AU_CO_NN NOT NULL;
ALTER TABLE AUTOMOVIL MODIFY n_asiento CONSTRAINT AU_NA_NN NOT NULL;
ALTER TABLE AUTOMOVIL MODIFY pais CONSTRAINT AU_PA_NN NOT NULL;
ALTER TABLE AUTOMOVIL MODIFY año CONSTRAINT AU_AÑ_NN NOT NULL;
-- -- Asigna restriccion de valores para los atributos
ALTER TABLE AUTOMOVIL ADD CONSTRAINT AU_CO_CHK CHECK(color='ROJO' OR color='AZUL' OR color='VERDE');
ALTER TABLE AUTOMOVIL ADD CONSTRAINT AU_NA_CHK CHECK(n_asiento BETWEEN 2 AND 8);
ALTER TABLE AUTOMOVIL ADD CONSTRAINT AU_PA_CHK CHECK(pais='JAPON' OR pais='USA' OR pais='CHINA');
ALTER TABLE AUTOMOVIL ADD CONSTRAINT AU_AÑ_CHK CHECK(año BETWEEN 2000 AND 2024);
-- Agregamos datos a la tabla AUTOMOVIL
INSERT INTO AUTOMOVIL VALUES('SGAT-11', 'ROJO', 2, 'JAPON', 2024);
INSERT INTO AUTOMOVIL VALUES('SHSA-12', 'AZUL', 3, 'USA', 2020);
INSERT INTO AUTOMOVIL VALUES('WASD-10', 'VERDE', 4, 'USA', 2000);
INSERT INTO AUTOMOVIL VALUES('ASDF-12', 'VERDE', 5, 'USA', 2006);
INSERT INTO AUTOMOVIL VALUES('QWER-01', 'AZUL', 6, 'CHINA', 2019);
INSERT INTO AUTOMOVIL VALUES('ZXCV-23', 'ROJO', 7, 'CHINA', 2010);
INSERT INTO AUTOMOVIL VALUES('VCZS-01', 'AZUL', 8, 'USA', 2012);
INSERT INTO AUTOMOVIL VALUES('VCZS-07', 'AZUL', 4, 'JAPON', 2014);
-- Visualicemos la tabla AUTOMOVIL
SELECT * FROM AUTOMOVIL;
-- Crear la tabla MARCA
CREATE TABLE MARCA(cod_marca NUMERIC(3),
                   nom_marca VARCHAR2(25));
-- Crearemos las constraints
-- -- Asigna cod_marca como primary key
ALTER TABLE MARCA ADD CONSTRAINT MA_CM_PK PRIMARY KEY(cod_marca);
-- -- Deja en no nulos estos atributos
ALTER TABLE MARCA MODIFY nom_marca CONSTRAINT MA_NM_NN NOT NULL;
-- Agregamos datos a la tabla MARCA
INSERT INTO MARCA VALUES('001', 'TOYOTA');
INSERT INTO MARCA VALUES('002', 'NISSAN');
INSERT INTO MARCA VALUES('003', 'FORD');
-- Visualicemos la tabla MARCA
SELECT * FROM MARCA;
-- Relacionar tabla MARCA con AUTOMOVIL
-- -- Agregar el cod_marca a AUTOMOVIL
ALTER TABLE AUTOMOVIL ADD cod_marca NUMERIC(3);
-- -- Asignamos la foreign key a AUTOMOVIL
ALTER TABLE AUTOMOVIL ADD CONSTRAINT AU_CM_FK FOREIGN KEY (cod_marca)
REFERENCES MARCA(cod_marca);
-- Usamos la referencia de MARCA para llenar el atributo cod_marca de AUTOMOVIL
UPDATE AUTOMOVIL SET cod_marca = 001;
-- Sin WHERE es a todos
CREATE TABLE DUEÑO(run NUMERIC(8), 
                   dv VARCHAR2(1), 
                   nombre VARCHAR2(30),
                   apellido VARCHAR2(30));
                   
ALTER TABLE DUEÑO ADD CONSTRAINT DU_RU_PK PRIMARY KEY(run);
ALTER TABLE DUEÑO MODIFY dv CONSTRAINT DU_DV_NN NOT NULL;
ALTER TABLE DUEÑO MODIFY nombre CONSTRAINT DU_NO_NN NOT NULL;
ALTER TABLE DUEÑO MODIFY apellido CONSTRAINT DU_AP_NN NOT NULL;

INSERT INTO DUEÑO VALUES('01964923', '2', 'MARCO', 'ZAPATA');

ALTER TABLE AUTOMOVIL ADD run NUMERIC(8);
ALTER TABLE AUTOMOVIL ADD CONSTRAINT AU_RU_FK FOREIGN KEY (run)
REFERENCES DUEÑO(run);
UPDATE AUTOMOVIL SET run = 01964923;

SELECT * FROM AUTOMOVIL;